# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 18:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='url',
            field=models.URLField(verbose_name='URL'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together=set([('url', 'user')]),
        ),
    ]
