# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-15 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmarks', '0005_auto_20170915_1015'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='collections',
            field=models.ManyToManyField(to='bookmarks.Collection'),
        ),
    ]
