# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-14 20:24
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import profiles.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(blank=True, default='', max_length=50)),
                ('last_name', models.CharField(blank=True, default='', max_length=50)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=profiles.models.avatar_upload_path, verbose_name='Avatar picture')),
                ('bio', models.TextField(default='', verbose_name='Short Bio')),
            ],
        ),
    ]
